/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author CemArslan
 */
public class Admin_Decrease_Parking_Lot extends javax.swing.JFrame {

    /**
     * Creates new form Admin_Decrease_Parking_Lot
     */
    public Admin_Decrease_Parking_Lot() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNumOfParkingLotsToREMOVE = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnDECREASEnumberOfParkingLots = new javax.swing.JButton();
        btnBackToAdminSettingsMain = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setBackground(new java.awt.Color(153, 255, 255));
        jInternalFrame1.setClosable(true);
        jInternalFrame1.setIconifiable(true);
        jInternalFrame1.setMaximizable(true);
        jInternalFrame1.setResizable(true);
        jInternalFrame1.setVisible(true);
        jInternalFrame1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CentralAutoParkingProject/settings.png"))); // NOI18N
        jLabel1.setText("           ADMIN SETTINGS");
        jInternalFrame1.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 288));

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Here, you can DECREASE hte number of parking lots:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 48, -1, -1));

        txtNumOfParkingLotsToREMOVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumOfParkingLotsToREMOVEActionPerformed(evt);
            }
        });
        jPanel1.add(txtNumOfParkingLotsToREMOVE, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 136, 225, 33));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("How many parking lots you want to remove? :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 143, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(759, 136, -1, -1));

        btnDECREASEnumberOfParkingLots.setBackground(new java.awt.Color(0, 255, 51));
        btnDECREASEnumberOfParkingLots.setForeground(new java.awt.Color(0, 153, 0));
        btnDECREASEnumberOfParkingLots.setText("DECREASE");
        btnDECREASEnumberOfParkingLots.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDECREASEnumberOfParkingLotsActionPerformed(evt);
            }
        });
        jPanel1.add(btnDECREASEnumberOfParkingLots, new org.netbeans.lib.awtextra.AbsoluteConstraints(616, 187, 139, 46));

        btnBackToAdminSettingsMain.setBackground(new java.awt.Color(255, 0, 51));
        btnBackToAdminSettingsMain.setForeground(new java.awt.Color(255, 0, 51));
        btnBackToAdminSettingsMain.setText("BACK TO ADMIN SETTINGS MENU");
        btnBackToAdminSettingsMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToAdminSettingsMainActionPerformed(evt);
            }
        });
        jPanel1.add(btnBackToAdminSettingsMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, 46));

        jInternalFrame1.getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 299, 870, 290));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("REMOVE PARKING LOT");
        jInternalFrame1.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 905, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1, javax.swing.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumOfParkingLotsToREMOVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumOfParkingLotsToREMOVEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumOfParkingLotsToREMOVEActionPerformed

    private void btnDECREASEnumberOfParkingLotsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDECREASEnumberOfParkingLotsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDECREASEnumberOfParkingLotsActionPerformed

    private void btnBackToAdminSettingsMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToAdminSettingsMainActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackToAdminSettingsMainActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_Decrease_Parking_Lot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_Decrease_Parking_Lot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_Decrease_Parking_Lot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Decrease_Parking_Lot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_Decrease_Parking_Lot().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackToAdminSettingsMain;
    private javax.swing.JButton btnDECREASEnumberOfParkingLots;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtNumOfParkingLotsToREMOVE;
    // End of variables declaration//GEN-END:variables
}

