/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author CemArslan
 */
public class Admin_Add_NewCars extends javax.swing.JFrame {

    /**
     * Creates new form User_side_Subscription
     */
    public Admin_Add_NewCars() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        txtDriverNationalID = new javax.swing.JTextField();
        txtDriverSurname = new javax.swing.JTextField();
        txtDriverName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDriverAge = new javax.swing.JTextField();
        radioCommercial = new javax.swing.JRadioButton();
        radioPrivate = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCarModel = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtCarPlate = new javax.swing.JTextField();
        txtCarBrand = new javax.swing.JTextField();
        btnSaveNewDriverSubscription = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        btnBackToAdminSettingMainMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setBackground(new java.awt.Color(153, 255, 255));
        jInternalFrame1.setClosable(true);
        jInternalFrame1.setIconifiable(true);
        jInternalFrame1.setMaximizable(true);
        jInternalFrame1.setResizable(true);
        jInternalFrame1.setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/CentralAutoParkingProject/31926R-MAI-RED-Volkswagen-Beetle-Hard-Top-Diecast-Model-Toy-Car-det.jpg"))); // NOI18N
        jInternalFrame1.setVisible(true);
        jInternalFrame1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(153, 153, 0));
        jLabel1.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CentralAutoParkingProject/download.png"))); // NOI18N
        jLabel1.setText("    WELCOME TO MEL-CEM BROTHERS AUTO PARK");
        jInternalFrame1.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 990, 140));

        txtDriverNationalID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDriverNationalIDActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(txtDriverNationalID, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 240, 40));
        jInternalFrame1.getContentPane().add(txtDriverSurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 240, 40));

        txtDriverName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDriverNameActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(txtDriverName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 240, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("SUBSCRIPTION FORM");
        jInternalFrame1.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 270, -1));

        txtDriverAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDriverAgeActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(txtDriverAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 440, 240, 40));

        radioCommercial.setBackground(new java.awt.Color(153, 255, 255));
        radioCommercial.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        radioCommercial.setText("Commercial Vehicle");
        jInternalFrame1.getContentPane().add(radioCommercial, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 440, -1, -1));

        radioPrivate.setBackground(new java.awt.Color(153, 255, 255));
        radioPrivate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        radioPrivate.setText("Private Car");
        jInternalFrame1.getContentPane().add(radioPrivate, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 440, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Driver Surname:");
        jInternalFrame1.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Driver National ID:");
        jInternalFrame1.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Car Type:");
        jInternalFrame1.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 440, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Driver Name:");
        jInternalFrame1.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Driver Age:");
        jInternalFrame1.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Car Model Name:");
        jInternalFrame1.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 390, -1, -1));
        jInternalFrame1.getContentPane().add(txtCarModel, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 380, 270, 40));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Car Plate:");
        jInternalFrame1.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 270, -1, -1));

        jLabel10.setText("For Commercial Vehicle 500$ per mounthy.");
        jInternalFrame1.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 460, 330, 30));

        jLabel11.setText("For Private Car 350$ per mounthy.");
        jInternalFrame1.getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 480, -1, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Car Brand:");
        jInternalFrame1.getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, -1, -1));
        jInternalFrame1.getContentPane().add(txtCarPlate, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 260, 270, 40));
        jInternalFrame1.getContentPane().add(txtCarBrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 320, 270, 40));

        btnSaveNewDriverSubscription.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSaveNewDriverSubscription.setText("SAVE SUBSCRIPTION");
        btnSaveNewDriverSubscription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveNewDriverSubscriptionActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(btnSaveNewDriverSubscription, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 510, 170, 40));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 0, 51));
        jLabel13.setText("This form is filled by Admin and a filled hard copy will be given to the Drivers.");
        jInternalFrame1.getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 610, 90));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Phone Number:");
        jInternalFrame1.getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, -1, -1));
        jInternalFrame1.getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 510, 240, 40));

        btnBackToAdminSettingMainMenu.setText("BACK TO MAIN ADMIN SETTINGS MENU");
        btnBackToAdminSettingMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToAdminSettingMainMenuActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(btnBackToAdminSettingMainMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 510, 260, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
        );

        try {
            jInternalFrame1.setIcon(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDriverNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDriverNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDriverNameActionPerformed

    private void txtDriverNationalIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDriverNationalIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDriverNationalIDActionPerformed

    private void txtDriverAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDriverAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDriverAgeActionPerformed

    private void btnSaveNewDriverSubscriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveNewDriverSubscriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveNewDriverSubscriptionActionPerformed

    private void btnBackToAdminSettingMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToAdminSettingMainMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackToAdminSettingMainMenuActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackToAdminSettingMainMenu;
    private javax.swing.JButton btnSaveNewDriverSubscription;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JRadioButton radioCommercial;
    private javax.swing.JRadioButton radioPrivate;
    private javax.swing.JTextField txtCarBrand;
    private javax.swing.JTextField txtCarModel;
    private javax.swing.JTextField txtCarPlate;
    private javax.swing.JTextField txtDriverAge;
    private javax.swing.JTextField txtDriverName;
    private javax.swing.JTextField txtDriverNationalID;
    private javax.swing.JTextField txtDriverSurname;
    // End of variables declaration//GEN-END:variables
}

