/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author CemArslan
 */
public class AdminDisplayAllSUBSCRIPTIONS extends javax.swing.JFrame {

    /**
     * Creates new form AdminDisplayAllSUBSCRIPTIONS
     */
    public AdminDisplayAllSUBSCRIPTIONS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        btnBackToAdminSettingsMenu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDisplayAllSUBSCRIPTIONS = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setBackground(new java.awt.Color(204, 255, 204));
        jInternalFrame1.setClosable(true);
        jInternalFrame1.setIconifiable(true);
        jInternalFrame1.setMaximizable(true);
        jInternalFrame1.setResizable(true);
        jInternalFrame1.setVisible(true);
        jInternalFrame1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBackToAdminSettingsMenu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBackToAdminSettingsMenu.setText("BACK TO ADMIN SETTING MENU");
        btnBackToAdminSettingsMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToAdminSettingsMenuActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(btnBackToAdminSettingsMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, 279, 59));

        txtDisplayAllSUBSCRIPTIONS.setColumns(20);
        txtDisplayAllSUBSCRIPTIONS.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        txtDisplayAllSUBSCRIPTIONS.setRows(5);
        txtDisplayAllSUBSCRIPTIONS.setText("#EXAMPLE RUN\n\n\nCURRENTLY, THERE ARE 2 CARS' SUBSCRIBTIONS.\n\nDriver Name: Cem\nDriver Surname: ARSLAN\nAge: 22\nCar Plate: 34 HR 841\nCar Brand: Fiat\nCar Model: Egea\nCar Type: Private Car\nContact : +90 554 852 78 50\n\nDriver Name: Melikşah\nDriver Surname: ÖZCEYHAN\nAge: 22\nCar Plate: 34 YZ 516\nCar Brand: Fiat\nCar Model: Doblo :D\nCar Type: Commercial Car\nContact : +90 123 456 78 90\n\n\n\n");
        jScrollPane1.setViewportView(txtDisplayAllSUBSCRIPTIONS);

        jInternalFrame1.getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 513, 350));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("CURRENTLY,ALL MOUNTHLY SUBSCRIPTIONS ARE SHOWN BELOW");
        jInternalFrame1.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 480, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackToAdminSettingsMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToAdminSettingsMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackToAdminSettingsMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDisplayAllSUBSCRIPTIONS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDisplayAllSUBSCRIPTIONS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDisplayAllSUBSCRIPTIONS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDisplayAllSUBSCRIPTIONS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDisplayAllSUBSCRIPTIONS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackToAdminSettingsMenu;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtDisplayAllSUBSCRIPTIONS;
    // End of variables declaration//GEN-END:variables
}

