/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author CemArslan
 */
public class Admn_Increase_ParkingLot extends javax.swing.JFrame {

    /**
     * Creates new form Admn_Increase_ParkingLot
     */
    public Admn_Increase_ParkingLot() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNumOfParkingLotsToINCREASE = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnINCREASEnumberOfParkingLots = new javax.swing.JButton();
        btnGoBackToAdminSettingsMain = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setBackground(new java.awt.Color(153, 255, 255));
        jInternalFrame1.setClosable(true);
        jInternalFrame1.setIconifiable(true);
        jInternalFrame1.setMaximizable(true);
        jInternalFrame1.setResizable(true);
        jInternalFrame1.setVisible(true);
        jInternalFrame1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CentralAutoParkingProject/settings.png"))); // NOI18N
        jLabel1.setText("               ADMIN SETTINGS");
        jInternalFrame1.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 288));

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Here, you can DECREASE hte number of parking lots:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 48, -1, -1));

        txtNumOfParkingLotsToINCREASE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumOfParkingLotsToINCREASEActionPerformed(evt);
            }
        });
        jPanel1.add(txtNumOfParkingLotsToINCREASE, new org.netbeans.lib.awtextra.AbsoluteConstraints(546, 136, 225, 33));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("How many NEW parking lots you want to ADD? :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 143, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(775, 136, -1, -1));

        btnINCREASEnumberOfParkingLots.setBackground(new java.awt.Color(0, 255, 51));
        btnINCREASEnumberOfParkingLots.setForeground(new java.awt.Color(0, 153, 0));
        btnINCREASEnumberOfParkingLots.setText("INCREASE");
        btnINCREASEnumberOfParkingLots.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnINCREASEnumberOfParkingLotsActionPerformed(evt);
            }
        });
        jPanel1.add(btnINCREASEnumberOfParkingLots, new org.netbeans.lib.awtextra.AbsoluteConstraints(546, 187, 225, 46));

        btnGoBackToAdminSettingsMain.setBackground(new java.awt.Color(255, 0, 51));
        btnGoBackToAdminSettingsMain.setForeground(new java.awt.Color(255, 0, 51));
        btnGoBackToAdminSettingsMain.setText("BACK TO ADMIN SETTINGS MENU");
        btnGoBackToAdminSettingsMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoBackToAdminSettingsMainActionPerformed(evt);
            }
        });
        jPanel1.add(btnGoBackToAdminSettingsMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, 46));

        jInternalFrame1.getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 299, 870, 270));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("ADD NEW PARKING LOTS");
        jInternalFrame1.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, -1, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 905, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumOfParkingLotsToINCREASEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumOfParkingLotsToINCREASEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumOfParkingLotsToINCREASEActionPerformed

    private void btnINCREASEnumberOfParkingLotsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnINCREASEnumberOfParkingLotsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnINCREASEnumberOfParkingLotsActionPerformed

    private void btnGoBackToAdminSettingsMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoBackToAdminSettingsMainActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGoBackToAdminSettingsMainActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admn_Increase_ParkingLot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admn_Increase_ParkingLot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admn_Increase_ParkingLot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admn_Increase_ParkingLot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admn_Increase_ParkingLot().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGoBackToAdminSettingsMain;
    private javax.swing.JButton btnINCREASEnumberOfParkingLots;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtNumOfParkingLotsToINCREASE;
    // End of variables declaration//GEN-END:variables
}

