/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author CemArslan
 */
public class EnteringRecognizingCamera extends javax.swing.JFrame {

    /**
     * Creates new form CameraRecordings
     */
    public EnteringRecognizingCamera() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnBackToMaınMenu = new javax.swing.JButton();
        btnRecognizeCar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaEnteringCarInformationDisplay = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        txtEnteringCarPlateRecognition = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setVisible(true);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CentralAutoParkingProject/287817-200.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("System's Camera Is Recognizing The Car Automaticaly!");

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBackToMaınMenu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBackToMaınMenu.setForeground(new java.awt.Color(255, 0, 51));
        btnBackToMaınMenu.setText("BACK TO MAIN MENU");
        btnBackToMaınMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToMaınMenuActionPerformed(evt);
            }
        });
        jPanel1.add(btnBackToMaınMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 170, 48));

        btnRecognizeCar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRecognizeCar.setForeground(new java.awt.Color(0, 204, 51));
        btnRecognizeCar.setText("Recognize My Car");
        btnRecognizeCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecognizeCarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRecognizeCar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 250, 150, 48));

        jLabel3.setText("RECORNIZING CAR PLATE :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 160, 30));

        txtAreaEnteringCarInformationDisplay.setColumns(20);
        txtAreaEnteringCarInformationDisplay.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        txtAreaEnteringCarInformationDisplay.setRows(5);
        txtAreaEnteringCarInformationDisplay.setText("#EXAMPLE 1\nWELCOME TO MEL-CEM AUTO PARK\nAUTO PARK IS AVAILABLE\nYOUR STATUS IS MOUNTHLY/DAILY SUBSCRIPTION\nGATE IS OPENED\nPLEASE PROGRESS TOWARD AUTO PARK.\n\n#EXAMPLE 2\nOopps...! Sorry,\nAUTO PARK IS FULL!\nSee You Later!");
        jScrollPane1.setViewportView(txtAreaEnteringCarInformationDisplay);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, 339, 201));

        jLabel4.setText("INFORMATION");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, -1, -1));

        txtEnteringCarPlateRecognition.setText("#type the PLATE MANUALLY");
        txtEnteringCarPlateRecognition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnteringCarPlateRecognitionActionPerformed(evt);
            }
        });
        jPanel1.add(txtEnteringCarPlateRecognition, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 250, 40));

        jLabel5.setText("your subscription type and auto park's availibility.");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 430, 40));

        jLabel6.setText("Click Recognize My Car button to recognize ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 260, 30));

        jLabel7.setText("If the result is possitive, you will be added to CAR INSIDE list.--------->");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 420, 50));

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEnteringCarPlateRecognitionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnteringCarPlateRecognitionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnteringCarPlateRecognitionActionPerformed

    private void btnRecognizeCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecognizeCarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRecognizeCarActionPerformed

    private void btnBackToMaınMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToMaınMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackToMaınMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnteringRecognizingCamera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnteringRecognizingCamera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnteringRecognizingCamera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnteringRecognizingCamera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EnteringRecognizingCamera().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackToMaınMenu;
    private javax.swing.JButton btnRecognizeCar;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtAreaEnteringCarInformationDisplay;
    private javax.swing.JTextField txtEnteringCarPlateRecognition;
    // End of variables declaration//GEN-END:variables
}

