/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author CemArslan
 */
public class ExitingRecognizingCamera extends javax.swing.JFrame {

    /**
     * Creates new form ExitingRecognizingCamera
     */
    public ExitingRecognizingCamera() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnBackToMaınMenu = new javax.swing.JButton();
        btnRecognizeExittingCar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtExittingINFORMATIONDisplay = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        txtExittingCarPlate = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setVisible(true);
        jInternalFrame1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CentralAutoParkingProject/287817-200.png"))); // NOI18N
        jInternalFrame1.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 190, 193));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("System's Camera Is Recognizing The Car Automaticaly!");
        jInternalFrame1.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 58, 570, 87));

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBackToMaınMenu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBackToMaınMenu.setForeground(new java.awt.Color(255, 0, 51));
        btnBackToMaınMenu.setText("BACK TO MAIN MENU");
        btnBackToMaınMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToMaınMenuActionPerformed(evt);
            }
        });
        jPanel1.add(btnBackToMaınMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 170, 48));

        btnRecognizeExittingCar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRecognizeExittingCar.setForeground(new java.awt.Color(0, 204, 51));
        btnRecognizeExittingCar.setText("Recognize My Car - Remove From Insıde Cars List");
        btnRecognizeExittingCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecognizeExittingCarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRecognizeExittingCar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, 390, 48));

        jLabel3.setText("RECORNIZING CAR PLATE :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 160, 30));

        txtExittingINFORMATIONDisplay.setColumns(20);
        txtExittingINFORMATIONDisplay.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        txtExittingINFORMATIONDisplay.setRows(5);
        txtExittingINFORMATIONDisplay.setText("#EXAMPLE RUN\nYOU DO NOT HAVE MOUNTHLY SUBSCRIPTION!\nYou are charged as DAILY SUBSCRIPTION\nTotal hours inside : 3 hours.\nPer hour inside : 5$.\n\nPlease pay 15$ to the clerk and then you\ncan leave the auto park.\nThank you,hope to see you again!\n\n#EXAMPLE RUN 2\nPRECIOUS SUBSCRIBER CEM ARSLAN\nThank you, hope to see you again!\n");
        jScrollPane1.setViewportView(txtExittingINFORMATIONDisplay);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, 38, 339, 201));

        jLabel4.setText("INFORMATION");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, -1, -1));

        txtExittingCarPlate.setText("#type the PLATE MANUALLY");
        txtExittingCarPlate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtExittingCarPlateActionPerformed(evt);
            }
        });
        jPanel1.add(txtExittingCarPlate, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 250, 40));

        jLabel5.setText("your subscription type and parking fee.");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 430, 40));

        jLabel6.setText("Click \"Recognize My Car...\" button to recognize ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 280, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Thank you for choosing us!");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 200, -1));

        jInternalFrame1.getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 781, 346));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 822, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackToMaınMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToMaınMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackToMaınMenuActionPerformed

    private void btnRecognizeExittingCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecognizeExittingCarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRecognizeExittingCarActionPerformed

    private void txtExittingCarPlateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtExittingCarPlateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtExittingCarPlateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExitingRecognizingCamera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExitingRecognizingCamera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExitingRecognizingCamera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExitingRecognizingCamera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExitingRecognizingCamera().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackToMaınMenu;
    private javax.swing.JButton btnRecognizeExittingCar;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtExittingCarPlate;
    private javax.swing.JTextArea txtExittingINFORMATIONDisplay;
    // End of variables declaration//GEN-END:variables
}

